[package]
name = "dupels-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dupels-lib = { path = "../dupels-lib" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3.7.0"